version: '3'

services:
  api-buttons-react:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    container_name: api-buttons-react
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm start